name: Scala CI
env:
  CIRCT_VERSION: sifive/1/22/1

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Install CIRCT
        run: |
          mkdir usr
          CIRCT_VERSION_ESCAPED=`echo ${{ env.CIRCT_VERSION }} | sed 's/\//%2F/g'`
          wget https://github.com/llvm/circt/releases/download/$CIRCT_VERSION_ESCAPED/circt-bin-ubuntu-20.04.tar.gz -O - | tar -zx -C usr/
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH
      - name: Setup and run tests
        run: sbt +test
      - name: Check Formatting
        run: sbt scalafmtCheckAll

  publish:
    needs: [test]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
